title: Open Source Compliance
author: Henrik Sandklef
description: All about Open Source Compliance 
theme: jekyll-theme-cayman
github:
  is_project_page: false
include: ['pages', 'pages/tooling' ] 